// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: styles.proto

package io.slinkydeveloper.brewery.styles;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:styles.Empty)
    com.google.protobuf.MessageOrBuilder {
}
