// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: styles.proto

package io.slinkydeveloper.brewery.styles;

public interface StyleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:styles.Style)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 3;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
