// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: styles.proto

package io.slinkydeveloper.brewery.styles;

public interface StylesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:styles.Styles)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .styles.Style styles = 1;</code>
   */
  java.util.List<io.slinkydeveloper.brewery.styles.Style> 
      getStylesList();
  /**
   * <code>repeated .styles.Style styles = 1;</code>
   */
  io.slinkydeveloper.brewery.styles.Style getStyles(int index);
  /**
   * <code>repeated .styles.Style styles = 1;</code>
   */
  int getStylesCount();
  /**
   * <code>repeated .styles.Style styles = 1;</code>
   */
  java.util.List<? extends io.slinkydeveloper.brewery.styles.StyleOrBuilder> 
      getStylesOrBuilderList();
  /**
   * <code>repeated .styles.Style styles = 1;</code>
   */
  io.slinkydeveloper.brewery.styles.StyleOrBuilder getStylesOrBuilder(
      int index);
}
