// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: styles.proto

package io.slinkydeveloper.brewery.styles;

public final class StylesGRPC {
  private StylesGRPC() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_styles_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_styles_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_styles_StyleId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_styles_StyleId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_styles_NewStyle_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_styles_NewStyle_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_styles_Style_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_styles_Style_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_styles_Styles_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_styles_Styles_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014styles.proto\022\006styles\"\007\n\005Empty\"\025\n\007Style" +
      "Id\022\n\n\002id\030\001 \001(\003\"-\n\010NewStyle\022\014\n\004name\030\001 \001(\t" +
      "\022\023\n\013description\030\002 \001(\t\"6\n\005Style\022\n\n\002id\030\001 \001" +
      "(\003\022\014\n\004name\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\"\'\n" +
      "\006Styles\022\035\n\006styles\030\001 \003(\0132\r.styles.Style2\315" +
      "\001\n\rStylesService\022,\n\010GetStyle\022\017.styles.St" +
      "yleId\032\r.styles.Style\"\000\022,\n\tGetStyles\022\r.st" +
      "yles.Empty\032\016.styles.Styles\"\000\022/\n\010AddStyle" +
      "\022\020.styles.NewStyle\032\017.styles.StyleId\"\000\022/\n" +
      "\013RemoveStyle\022\017.styles.StyleId\032\r.styles.E",
      "mpty\"\000B1\n!io.slinkydeveloper.brewery.sty" +
      "lesB\nStylesGRPCP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_styles_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_styles_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_styles_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_styles_StyleId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_styles_StyleId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_styles_StyleId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_styles_NewStyle_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_styles_NewStyle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_styles_NewStyle_descriptor,
        new java.lang.String[] { "Name", "Description", });
    internal_static_styles_Style_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_styles_Style_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_styles_Style_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", });
    internal_static_styles_Styles_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_styles_Styles_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_styles_Styles_descriptor,
        new java.lang.String[] { "Styles", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
