// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: styles.proto

package io.slinkydeveloper.brewery.styles;

/**
 * Protobuf type {@code styles.Styles}
 */
public  final class Styles extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:styles.Styles)
    StylesOrBuilder {
  // Use Styles.newBuilder() to construct.
  private Styles(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Styles() {
    styles_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Styles(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              styles_ = new java.util.ArrayList<io.slinkydeveloper.brewery.styles.Style>();
              mutable_bitField0_ |= 0x00000001;
            }
            styles_.add(
                input.readMessage(io.slinkydeveloper.brewery.styles.Style.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        styles_ = java.util.Collections.unmodifiableList(styles_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.slinkydeveloper.brewery.styles.StylesGRPC.internal_static_styles_Styles_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.slinkydeveloper.brewery.styles.StylesGRPC.internal_static_styles_Styles_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.slinkydeveloper.brewery.styles.Styles.class, io.slinkydeveloper.brewery.styles.Styles.Builder.class);
  }

  public static final int STYLES_FIELD_NUMBER = 1;
  private java.util.List<io.slinkydeveloper.brewery.styles.Style> styles_;
  /**
   * <code>repeated .styles.Style styles = 1;</code>
   */
  public java.util.List<io.slinkydeveloper.brewery.styles.Style> getStylesList() {
    return styles_;
  }
  /**
   * <code>repeated .styles.Style styles = 1;</code>
   */
  public java.util.List<? extends io.slinkydeveloper.brewery.styles.StyleOrBuilder> 
      getStylesOrBuilderList() {
    return styles_;
  }
  /**
   * <code>repeated .styles.Style styles = 1;</code>
   */
  public int getStylesCount() {
    return styles_.size();
  }
  /**
   * <code>repeated .styles.Style styles = 1;</code>
   */
  public io.slinkydeveloper.brewery.styles.Style getStyles(int index) {
    return styles_.get(index);
  }
  /**
   * <code>repeated .styles.Style styles = 1;</code>
   */
  public io.slinkydeveloper.brewery.styles.StyleOrBuilder getStylesOrBuilder(
      int index) {
    return styles_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < styles_.size(); i++) {
      output.writeMessage(1, styles_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < styles_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, styles_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.slinkydeveloper.brewery.styles.Styles)) {
      return super.equals(obj);
    }
    io.slinkydeveloper.brewery.styles.Styles other = (io.slinkydeveloper.brewery.styles.Styles) obj;

    boolean result = true;
    result = result && getStylesList()
        .equals(other.getStylesList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getStylesCount() > 0) {
      hash = (37 * hash) + STYLES_FIELD_NUMBER;
      hash = (53 * hash) + getStylesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.slinkydeveloper.brewery.styles.Styles parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.slinkydeveloper.brewery.styles.Styles parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.slinkydeveloper.brewery.styles.Styles parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.slinkydeveloper.brewery.styles.Styles parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.slinkydeveloper.brewery.styles.Styles parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.slinkydeveloper.brewery.styles.Styles parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.slinkydeveloper.brewery.styles.Styles parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.slinkydeveloper.brewery.styles.Styles parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.slinkydeveloper.brewery.styles.Styles parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.slinkydeveloper.brewery.styles.Styles parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.slinkydeveloper.brewery.styles.Styles prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code styles.Styles}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:styles.Styles)
      io.slinkydeveloper.brewery.styles.StylesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.slinkydeveloper.brewery.styles.StylesGRPC.internal_static_styles_Styles_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.slinkydeveloper.brewery.styles.StylesGRPC.internal_static_styles_Styles_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.slinkydeveloper.brewery.styles.Styles.class, io.slinkydeveloper.brewery.styles.Styles.Builder.class);
    }

    // Construct using io.slinkydeveloper.brewery.styles.Styles.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStylesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (stylesBuilder_ == null) {
        styles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        stylesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.slinkydeveloper.brewery.styles.StylesGRPC.internal_static_styles_Styles_descriptor;
    }

    public io.slinkydeveloper.brewery.styles.Styles getDefaultInstanceForType() {
      return io.slinkydeveloper.brewery.styles.Styles.getDefaultInstance();
    }

    public io.slinkydeveloper.brewery.styles.Styles build() {
      io.slinkydeveloper.brewery.styles.Styles result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.slinkydeveloper.brewery.styles.Styles buildPartial() {
      io.slinkydeveloper.brewery.styles.Styles result = new io.slinkydeveloper.brewery.styles.Styles(this);
      int from_bitField0_ = bitField0_;
      if (stylesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          styles_ = java.util.Collections.unmodifiableList(styles_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.styles_ = styles_;
      } else {
        result.styles_ = stylesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.slinkydeveloper.brewery.styles.Styles) {
        return mergeFrom((io.slinkydeveloper.brewery.styles.Styles)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.slinkydeveloper.brewery.styles.Styles other) {
      if (other == io.slinkydeveloper.brewery.styles.Styles.getDefaultInstance()) return this;
      if (stylesBuilder_ == null) {
        if (!other.styles_.isEmpty()) {
          if (styles_.isEmpty()) {
            styles_ = other.styles_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStylesIsMutable();
            styles_.addAll(other.styles_);
          }
          onChanged();
        }
      } else {
        if (!other.styles_.isEmpty()) {
          if (stylesBuilder_.isEmpty()) {
            stylesBuilder_.dispose();
            stylesBuilder_ = null;
            styles_ = other.styles_;
            bitField0_ = (bitField0_ & ~0x00000001);
            stylesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStylesFieldBuilder() : null;
          } else {
            stylesBuilder_.addAllMessages(other.styles_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.slinkydeveloper.brewery.styles.Styles parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.slinkydeveloper.brewery.styles.Styles) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<io.slinkydeveloper.brewery.styles.Style> styles_ =
      java.util.Collections.emptyList();
    private void ensureStylesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        styles_ = new java.util.ArrayList<io.slinkydeveloper.brewery.styles.Style>(styles_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.slinkydeveloper.brewery.styles.Style, io.slinkydeveloper.brewery.styles.Style.Builder, io.slinkydeveloper.brewery.styles.StyleOrBuilder> stylesBuilder_;

    /**
     * <code>repeated .styles.Style styles = 1;</code>
     */
    public java.util.List<io.slinkydeveloper.brewery.styles.Style> getStylesList() {
      if (stylesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(styles_);
      } else {
        return stylesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .styles.Style styles = 1;</code>
     */
    public int getStylesCount() {
      if (stylesBuilder_ == null) {
        return styles_.size();
      } else {
        return stylesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .styles.Style styles = 1;</code>
     */
    public io.slinkydeveloper.brewery.styles.Style getStyles(int index) {
      if (stylesBuilder_ == null) {
        return styles_.get(index);
      } else {
        return stylesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .styles.Style styles = 1;</code>
     */
    public Builder setStyles(
        int index, io.slinkydeveloper.brewery.styles.Style value) {
      if (stylesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStylesIsMutable();
        styles_.set(index, value);
        onChanged();
      } else {
        stylesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .styles.Style styles = 1;</code>
     */
    public Builder setStyles(
        int index, io.slinkydeveloper.brewery.styles.Style.Builder builderForValue) {
      if (stylesBuilder_ == null) {
        ensureStylesIsMutable();
        styles_.set(index, builderForValue.build());
        onChanged();
      } else {
        stylesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .styles.Style styles = 1;</code>
     */
    public Builder addStyles(io.slinkydeveloper.brewery.styles.Style value) {
      if (stylesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStylesIsMutable();
        styles_.add(value);
        onChanged();
      } else {
        stylesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .styles.Style styles = 1;</code>
     */
    public Builder addStyles(
        int index, io.slinkydeveloper.brewery.styles.Style value) {
      if (stylesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStylesIsMutable();
        styles_.add(index, value);
        onChanged();
      } else {
        stylesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .styles.Style styles = 1;</code>
     */
    public Builder addStyles(
        io.slinkydeveloper.brewery.styles.Style.Builder builderForValue) {
      if (stylesBuilder_ == null) {
        ensureStylesIsMutable();
        styles_.add(builderForValue.build());
        onChanged();
      } else {
        stylesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .styles.Style styles = 1;</code>
     */
    public Builder addStyles(
        int index, io.slinkydeveloper.brewery.styles.Style.Builder builderForValue) {
      if (stylesBuilder_ == null) {
        ensureStylesIsMutable();
        styles_.add(index, builderForValue.build());
        onChanged();
      } else {
        stylesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .styles.Style styles = 1;</code>
     */
    public Builder addAllStyles(
        java.lang.Iterable<? extends io.slinkydeveloper.brewery.styles.Style> values) {
      if (stylesBuilder_ == null) {
        ensureStylesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, styles_);
        onChanged();
      } else {
        stylesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .styles.Style styles = 1;</code>
     */
    public Builder clearStyles() {
      if (stylesBuilder_ == null) {
        styles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        stylesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .styles.Style styles = 1;</code>
     */
    public Builder removeStyles(int index) {
      if (stylesBuilder_ == null) {
        ensureStylesIsMutable();
        styles_.remove(index);
        onChanged();
      } else {
        stylesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .styles.Style styles = 1;</code>
     */
    public io.slinkydeveloper.brewery.styles.Style.Builder getStylesBuilder(
        int index) {
      return getStylesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .styles.Style styles = 1;</code>
     */
    public io.slinkydeveloper.brewery.styles.StyleOrBuilder getStylesOrBuilder(
        int index) {
      if (stylesBuilder_ == null) {
        return styles_.get(index);  } else {
        return stylesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .styles.Style styles = 1;</code>
     */
    public java.util.List<? extends io.slinkydeveloper.brewery.styles.StyleOrBuilder> 
         getStylesOrBuilderList() {
      if (stylesBuilder_ != null) {
        return stylesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(styles_);
      }
    }
    /**
     * <code>repeated .styles.Style styles = 1;</code>
     */
    public io.slinkydeveloper.brewery.styles.Style.Builder addStylesBuilder() {
      return getStylesFieldBuilder().addBuilder(
          io.slinkydeveloper.brewery.styles.Style.getDefaultInstance());
    }
    /**
     * <code>repeated .styles.Style styles = 1;</code>
     */
    public io.slinkydeveloper.brewery.styles.Style.Builder addStylesBuilder(
        int index) {
      return getStylesFieldBuilder().addBuilder(
          index, io.slinkydeveloper.brewery.styles.Style.getDefaultInstance());
    }
    /**
     * <code>repeated .styles.Style styles = 1;</code>
     */
    public java.util.List<io.slinkydeveloper.brewery.styles.Style.Builder> 
         getStylesBuilderList() {
      return getStylesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.slinkydeveloper.brewery.styles.Style, io.slinkydeveloper.brewery.styles.Style.Builder, io.slinkydeveloper.brewery.styles.StyleOrBuilder> 
        getStylesFieldBuilder() {
      if (stylesBuilder_ == null) {
        stylesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.slinkydeveloper.brewery.styles.Style, io.slinkydeveloper.brewery.styles.Style.Builder, io.slinkydeveloper.brewery.styles.StyleOrBuilder>(
                styles_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        styles_ = null;
      }
      return stylesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:styles.Styles)
  }

  // @@protoc_insertion_point(class_scope:styles.Styles)
  private static final io.slinkydeveloper.brewery.styles.Styles DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.slinkydeveloper.brewery.styles.Styles();
  }

  public static io.slinkydeveloper.brewery.styles.Styles getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Styles>
      PARSER = new com.google.protobuf.AbstractParser<Styles>() {
    public Styles parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Styles(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Styles> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Styles> getParserForType() {
    return PARSER;
  }

  public io.slinkydeveloper.brewery.styles.Styles getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

